from datetime import datetime

# Save chart
filename = f"charts/{s}.png"

mpf.plot(
    df,
    type="candle",
    style="yahoo",
    volume=True,
    addplot=apds,
    figsize=(15, 8),
    title=f"{s} | {datetime.now().day} {datetime.now().strftime('%b %y').lower()}",
    savefig=filename
)

# Send to Telegram
with open(filename, "rb") as photo:

    caption_text = (
        f"{s} | "
        f"{datetime.now().day} "
        f"{datetime.now().strftime('%b %y').lower()}"
    )

    response = requests.post(
        f"https://api.telegram.org/bot{BOT_TOKEN}/sendPhoto",
        data={
            "chat_id": CHAT_ID,
            "caption": caption_text
        },
        files={
            "photo": photo
        }
    )

    print(f"Telegram Response for {s}:")
    print(response.text)
